# This is a basic workflow to help you get started with Actions

name: actions

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2
    
      - name: artfact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{env.ARTIFACT}}
          path: .
          if-no-files-found: error
    


