# This is a basic workflow to help you get started with Actions

name: actions

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2
        with:
        - name: artifact
        - uses: actions/upload-artifact@v2.2.2
    


