# This is a basic workflow to help you get started with Actions

name: data-atual
on:
  push:
    branches: [main]
      
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        run: date
        
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        run: date 
        
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Step one
        run: date
        
    job4:
    name: Finish
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - name: Final step
        run: echo "Final step"
